version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    environment:
      - NEO4J_AUTH=neo4j/password  # Default credentials
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt Protocol for queries
    volumes:
      - neo4j_data:/data
      - ./migrations:/var/lib/neo4j/import  # Mount migrations folder

volumes:
  neo4j_data:
